### ISSUE TITLE
Logs from server

### ISSUE THREAD

**Issue by kasparpalgi** [crewnew/stat-ee#5]
Connected with Database...
Error: ORA-00933: SQL command not properly ended
Help:
[https://docs.oracle.com/error-help/db/ora-00933/](https://docs.oracle.com/error-help/db/ora-00933/?fbclid=IwZXh0bgNhZW0CMTAAAR2F7FyzvIT3rn4fNJ0jLDtD0P3rEHfoXfS4SNdaWFWKCEHZYu1OIcGbtEI_aem_iX3dHJYuOrIfpmvz_JGGXg)
    at Protocol._processMessage (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/protocol/protocol.js:181:17](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fprotocol%2Fprotocol.js%3A181%3A17%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR2FmAXJj8NzBdoWZi0ioye4wOBMWSHJCxCK-b72M-1ABEzXjW_fXAyRd4Q_aem_2OOCHlNionCDf6CyNYK2Gw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ThinConnectionImpl._execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:200:7](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A200%3A7%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR1_IWIa8NC6BVA_a5yuA91-4bShu943iZVfYxubB-7ky4ul3CccxuLhjzA_aem_U8VKUPwlN3kuHa4Wp78bPw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
    at async ThinConnectionImpl.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:880:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A880%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0Q2Xz4Ym-UTxULQX4_m04-dXV8rVOf38XNYxRyZWlsvhHBkJK_Yb2l1kE_aem_IfCrfbUKNNzq14mpCe-7-g&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
    at async Connection.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/connection.js:900:16](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fconnection.js%3A900%3A16%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0rKu68YyZgwniVLLVjRPxu2-w62qYoPm2kA3MshvDmAKzGECJqJq-Av8A_aem_Ata3dv8Edfyy9wbI3_t_Vw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
    at async Connection.<anonymous> (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/util.js:166:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Futil.js%3A166%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR13ukfUvE6bm41XOAQVkwS4J-WHCbu09SlouaTfv47sIhr-atJ5zKrpM2Q_aem_AOizysN9Mvuz-A_uq7Ksiw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) {
  offset: 199,
  errorNum: 933,
  code: 'ORA-00933'
}
Error: Query not found
    at /home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19](http://stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19?fbclid=IwZXh0bgNhZW0CMTAAAR2pGsBfe31axBoQIN4nG_pJZM77Lr98Wp-YDVks3l9PbiuCwEhpZoBIJ1g_aem_8GeCRvH5mp-BT0mMIGrlkw)
    at Generator.throw (<anonymous>)
    at rejected (/home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:6:65](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fdist%2Fsrc%2Finfrastructure%2Fdatabase_client%2Foracle.js%3A6%3A65%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3JzLWjdI5U1qOEP8H0GOITlRUOhqCojmyVVPlM98W__55Wb9ncOd-wYYo_aem__ejkJtoy9RxKC2RXoLoUdw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
connection released

**Comment by kasparpalgi** [comment]
The error message ORA-00933: SQL command not properly ended indicates that there is an issue with the syntax of the SQL statement being executed. This is a common error in Oracle databases and usually means that there is a mistake in the SQL query, such as a missing semicolon, incorrect use of keywords, or improper query formatting.

**Comment by kasparpalgi** [comment]
Oracle SQL statements executed via APIs should not include a terminating semicolon (;). But see - it found also another possible issue: "In the getMonthly function, the cluster identifier is hardcoded to 'a' instead of using the klaster parameter." and some other smaller issues: https://chatgpt.com/share/95773176-efc2-4e99-a5d3-a4dd95111470

**Comment by eapCJ** [comment]
> Connected with Database...
Error: ORA-00933: SQL command not properly ended
Help:
[https://docs.oracle.com/error-help/db/ora-00933/](https://docs.oracle.com/error-help/db/ora-00933/?fbclid=IwZXh0bgNhZW0CMTAAAR2F7FyzvIT3rn4fNJ0jLDtD0P3rEHfoXfS4SNdaWFWKCEHZYu1OIcGbtEI_aem_iX3dHJYuOrIfpmvz_JGGXg)
at Protocol._processMessage (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/protocol/protocol.js:181:17](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fprotocol%2Fprotocol.js%3A181%3A17%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR2FmAXJj8NzBdoWZi0ioye4wOBMWSHJCxCK-b72M-1ABEzXjW_fXAyRd4Q_aem_2OOCHlNionCDf6CyNYK2Gw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ThinConnectionImpl._execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:200:7](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A200%3A7%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR1_IWIa8NC6BVA_a5yuA91-4bShu943iZVfYxubB-7ky4ul3CccxuLhjzA_aem_U8VKUPwlN3kuHa4Wp78bPw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
at async ThinConnectionImpl.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:880:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A880%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0Q2Xz4Ym-UTxULQX4_m04-dXV8rVOf38XNYxRyZWlsvhHBkJK_Yb2l1kE_aem_IfCrfbUKNNzq14mpCe-7-g&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
at async Connection.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/connection.js:900:16](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fconnection.js%3A900%3A16%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0rKu68YyZgwniVLLVjRPxu2-w62qYoPm2kA3MshvDmAKzGECJqJq-Av8A_aem_Ata3dv8Edfyy9wbI3_t_Vw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
at async Connection. (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/util.js:166:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Futil.js%3A166%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR13ukfUvE6bm41XOAQVkwS4J-WHCbu09SlouaTfv47sIhr-atJ5zKrpM2Q_aem_AOizysN9Mvuz-A_uq7Ksiw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) {
offset: 199,
errorNum: 933,
code: 'ORA-00933'
}
Error: Query not found
at /home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19](http://stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19?fbclid=IwZXh0bgNhZW0CMTAAAR2pGsBfe31axBoQIN4nG_pJZM77Lr98Wp-YDVks3l9PbiuCwEhpZoBIJ1g_aem_8GeCRvH5mp-BT0mMIGrlkw)
at Generator.throw ()
at rejected (/home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:6:65](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fdist%2Fsrc%2Finfrastructure%2Fdatabase_client%2Foracle.js%3A6%3A65%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3JzLWjdI5U1qOEP8H0GOITlRUOhqCojmyVVPlM98W__55Wb9ncOd-wYYo_aem__ejkJtoy9RxKC2RXoLoUdw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s))
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
connection released



> Connected with Database... Error: ORA-00933: SQL command not properly ended Help: [https://docs.oracle.com/error-help/db/ora-00933/](https://docs.oracle.com/error-help/db/ora-00933/?fbclid=IwZXh0bgNhZW0CMTAAAR2F7FyzvIT3rn4fNJ0jLDtD0P3rEHfoXfS4SNdaWFWKCEHZYu1OIcGbtEI_aem_iX3dHJYuOrIfpmvz_JGGXg) at Protocol._processMessage (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/protocol/protocol.js:181:17](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fprotocol%2Fprotocol.js%3A181%3A17%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR2FmAXJj8NzBdoWZi0ioye4wOBMWSHJCxCK-b72M-1ABEzXjW_fXAyRd4Q_aem_2OOCHlNionCDf6CyNYK2Gw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ThinConnectionImpl._execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:200:7](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A200%3A7%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR1_IWIa8NC6BVA_a5yuA91-4bShu943iZVfYxubB-7ky4ul3CccxuLhjzA_aem_U8VKUPwlN3kuHa4Wp78bPw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) at async ThinConnectionImpl.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/thin/connection.js:880:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fthin%2Fconnection.js%3A880%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0Q2Xz4Ym-UTxULQX4_m04-dXV8rVOf38XNYxRyZWlsvhHBkJK_Yb2l1kE_aem_IfCrfbUKNNzq14mpCe-7-g&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) at async Connection.execute (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/connection.js:900:16](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Fconnection.js%3A900%3A16%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR0rKu68YyZgwniVLLVjRPxu2-w62qYoPm2kA3MshvDmAKzGECJqJq-Av8A_aem_Ata3dv8Edfyy9wbI3_t_Vw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) at async Connection. (/home/tonu.raitviir/[stat.ee/node_modules/oracledb/lib/util.js:166:14](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fnode_modules%2Foracledb%2Flib%2Futil.js%3A166%3A14%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR13ukfUvE6bm41XOAQVkwS4J-WHCbu09SlouaTfv47sIhr-atJ5zKrpM2Q_aem_AOizysN9Mvuz-A_uq7Ksiw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) { offset: 199, errorNum: 933, code: 'ORA-00933' } Error: Query not found at /home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19](http://stat.ee/dist/src/infrastructure/database_client/oracle.js:29:19?fbclid=IwZXh0bgNhZW0CMTAAAR2pGsBfe31axBoQIN4nG_pJZM77Lr98Wp-YDVks3l9PbiuCwEhpZoBIJ1g_aem_8GeCRvH5mp-BT0mMIGrlkw) at Generator.throw () at rejected (/home/tonu.raitviir/[stat.ee/dist/src/infrastructure/database_client/oracle.js:6:65](https://l.facebook.com/l.php?u=http%3A%2F%2Fstat.ee%2Fdist%2Fsrc%2Finfrastructure%2Fdatabase_client%2Foracle.js%3A6%3A65%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3JzLWjdI5U1qOEP8H0GOITlRUOhqCojmyVVPlM98W__55Wb9ncOd-wYYo_aem__ejkJtoy9RxKC2RXoLoUdw&h=AT0vfH9l_bNPeM9UJM6-xNPM75rWCW3W-kEYe7uXvL_d-2XxOxmtSlWnRO1mmL6eO0LoUQ03dhY25aqzgHCmxmuDh1x0M98fufCmWxNSuSPVLq1Zph05dsvN02SDbj8fIuHKMaHi7ne7QeDH22Wufb3s)) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) connection released

(See error docs)[https://docs.oracle.com/en/error-help/db/ora-00933/?r=23ai]

**Comment by eapCJ** [comment]
Tell Tonu Raitviir, I'll try fixing with the following:
> Oracle SQL statements executed via APIs should not include a terminating semicolon (;)

But if this fails, he has to provide us with an empty oracle database and access to it, otherwise we can stay on this error until forever,

**Comment by eapCJ** [comment]
#6
